<?php

declare(strict_types=1);

namespace App\Services\Import;

use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use ZipArchive;

/**
 * Handles ZIP import files generated by MemberFullExporter.
 *
 * Validates checksum, extracts CSV and documents,
 * copies documents to the correct member storage paths.
 *
 * Expected ZIP structure:
 *   commucore_export.json   ← metadata + checksums
 *   members_all.csv         ← member data
 *   documents/{id}_{slug}/  ← member documents
 */
final class ZipImportHandler
{
    private const DISK = 'local';

    private const EXTRACT_DIR = 'imports/extracted';

    private const MANIFEST_FILE = 'commucore_export.json';

    private const CSV_FILE = 'members_all.csv';

    /**
     * @return array{
     *     csv_path: string,
     *     manifest: array<string, mixed>,
     *     document_map: array<int, array{member_id: int, files: string[]}>,
     *     extract_dir: string,
     * }
     *
     * @throws \RuntimeException
     */
    public static function extract(UploadedFile $file): array
    {
        $extractDir = self::EXTRACT_DIR.'/'.str()->uuid();

        $zip = new ZipArchive;

        if ($zip->open($file->getRealPath()) !== true) {
            throw new \RuntimeException('Could not open ZIP archive.');
        }

        $absoluteExtractDir = Storage::disk(self::DISK)->path($extractDir);

        if (! is_dir($absoluteExtractDir)) {
            mkdir($absoluteExtractDir, 0755, recursive: true);
        }

        $zip->extractTo($absoluteExtractDir);
        $zip->close();

        // Manifest prüfen
        $manifest = self::readManifest($absoluteExtractDir);

        // Checksum prüfen
        self::verifyChecksum($absoluteExtractDir, $manifest);

        // CSV-Pfad
        $csvPath = $absoluteExtractDir.'/'.self::CSV_FILE;

        if (! file_exists($csvPath)) {
            throw new \RuntimeException('members_all.csv not found in ZIP.');
        }

        // Dokumente einlesen
        $documentMap = self::readDocumentMap($absoluteExtractDir);

        return [
            'csv_path' => $csvPath,
            'manifest' => $manifest,
            'document_map' => $documentMap,
            'extract_dir' => $absoluteExtractDir,
        ];
    }

    /**
     * Copy extracted documents to member storage paths.
     *
     * @param  array<int, array{member_id: int, files: string[]}>  $documentMap
     * @return array{copied: int, missing: int}
     */
    public static function copyDocuments(array $documentMap, string $storageDisk = 'local'): array
    {
        $copied = 0;
        $missing = 0;

        foreach ($documentMap as $entry) {
            $memberId = $entry['member_id'];

            foreach ($entry['files'] as $sourcePath) {
                if (! file_exists($sourcePath)) {
                    $missing++;

                    continue;
                }

                $filename = basename($sourcePath);
                $destination = sprintf('members/%d/documents/%s', $memberId, $filename);

                Storage::disk($storageDisk)->put(
                    $destination,
                    file_get_contents($sourcePath),
                );

                $copied++;
            }
        }

        return ['copied' => $copied, 'missing' => $missing];
    }

    /**
     * Clean up extracted files after import.
     */
    public static function cleanup(string $extractDir): void
    {
        self::deleteDirectory($extractDir);
    }

    /**
     * @return array<string, mixed>
     *
     * @throws \RuntimeException
     */
    private static function readManifest(string $extractDir): array
    {
        $manifestPath = $extractDir.'/'.self::MANIFEST_FILE;

        if (! file_exists($manifestPath)) {
            throw new \RuntimeException(
                'commucore_export.json not found – this ZIP was not exported from CommuCore.',
            );
        }

        $content = file_get_contents($manifestPath);

        if ($content === false) {
            throw new \RuntimeException('Could not read commucore_export.json.');
        }

        /** @var array<string, mixed> $manifest */
        $manifest = json_decode($content, associative: true);

        if (($manifest['app'] ?? '') !== 'commucore') {
            throw new \RuntimeException(
                'Invalid manifest: this ZIP was not exported from CommuCore.',
            );
        }

        return $manifest;
    }

    /**
     * @param  array<string, mixed>  $manifest
     *
     * @throws \RuntimeException
     */
    private static function verifyChecksum(string $extractDir, array $manifest): void
    {
        /** @var array<string, string> $checksums */
        $checksums = $manifest['checksums'] ?? [];

        foreach ($checksums as $filename => $expectedHash) {
            $filePath = $extractDir.'/'.$filename;

            if (! file_exists($filePath)) {
                throw new \RuntimeException("Checksum file not found: {$filename}");
            }

            $actualHash = 'sha256:'.hash_file('sha256', $filePath);

            if ($actualHash !== $expectedHash) {
                throw new \RuntimeException(
                    "Checksum mismatch for {$filename}. File may be corrupted or tampered.",
                );
            }
        }
    }

    /**
     * @return array<int, array{member_id: int, files: string[]}>
     */
    private static function readDocumentMap(string $extractDir): array
    {
        $documentsDir = $extractDir.'/documents';

        if (! is_dir($documentsDir)) {
            return [];
        }

        $map = [];
        $folders = scandir($documentsDir);

        if ($folders === false) {
            return [];
        }

        foreach ($folders as $folder) {
            if ($folder === '.' || $folder === '..') {
                continue;
            }

            // Ordnername: {member_id}_{slug}
            $parts = explode('_', $folder, 2);
            $memberId = (int) $parts[0];

            if ($memberId === 0) {
                continue;
            }

            $folderPath = $documentsDir.'/'.$folder;
            $files = scandir($folderPath);

            if ($files === false) {
                continue;
            }

            $filePaths = array_values(array_map(
                static fn (string $f): string => $folderPath.'/'.$f,
                array_filter(
                    $files,
                    static fn (string $f): bool => $f !== '.' && $f !== '..',
                ),
            ));

            $map[] = [
                'member_id' => $memberId,
                'files' => $filePaths,
            ];
        }

        return $map;
    }

    private static function deleteDirectory(string $dir): void
    {
        if (! is_dir($dir)) {
            return;
        }

        $items = scandir($dir);

        if ($items === false) {
            return;
        }

        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }

            $path = $dir.'/'.$item;

            is_dir($path) ? self::deleteDirectory($path) : unlink($path);
        }

        rmdir($dir);
    }
}
